package:
  name: tqdm
  version: 4.62.2
source:
  url: https://files.pythonhosted.org/packages/37/e5/1b54ef934d731576d0145bc8ae22da5b410f96922cec52b91cc29d3ff1b6/tqdm-4.62.2.tar.gz
  sha256: a4d6d112e507ef98513ac119ead1159d286deab17dffedd96921412c2d236ff5
test:
  imports:
  - tqdm
about:
  home: https://tqdm.github.io
  PyPi: https://pypi.org/project/tqdm
  summary: Fast, Extensible Progress Meter
  license: MPLv2.0, MIT Licences
